/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSimulationRouteImport } from './routes/_app.simulation'
import { Route as AppSignalQualityRouteImport } from './routes/_app.signal-quality'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppOrderPredictionRouteImport } from './routes/_app.order-prediction'
import { Route as AppModelResultsRouteImport } from './routes/_app.model-results'
import { Route as AppMerchantManagementRouteImport } from './routes/_app.merchant-management'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSimulationRoute = AppSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalQualityRoute = AppSignalQualityRouteImport.update({
  id: '/signal-quality',
  path: '/signal-quality',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderPredictionRoute = AppOrderPredictionRouteImport.update({
  id: '/order-prediction',
  path: '/order-prediction',
  getParentRoute: () => AppRoute,
} as any)
const AppModelResultsRoute = AppModelResultsRouteImport.update({
  id: '/model-results',
  path: '/model-results',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantManagementRoute = AppMerchantManagementRouteImport.update({
  id: '/merchant-management',
  path: '/merchant-management',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/merchant-management': typeof AppMerchantManagementRoute
  '/model-results': typeof AppModelResultsRoute
  '/order-prediction': typeof AppOrderPredictionRoute
  '/settings': typeof AppSettingsRoute
  '/signal-quality': typeof AppSignalQualityRoute
  '/simulation': typeof AppSimulationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/merchant-management': typeof AppMerchantManagementRoute
  '/model-results': typeof AppModelResultsRoute
  '/order-prediction': typeof AppOrderPredictionRoute
  '/settings': typeof AppSettingsRoute
  '/signal-quality': typeof AppSignalQualityRoute
  '/simulation': typeof AppSimulationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/merchant-management': typeof AppMerchantManagementRoute
  '/_app/model-results': typeof AppModelResultsRoute
  '/_app/order-prediction': typeof AppOrderPredictionRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signal-quality': typeof AppSignalQualityRoute
  '/_app/simulation': typeof AppSimulationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/merchant-management'
    | '/model-results'
    | '/order-prediction'
    | '/settings'
    | '/signal-quality'
    | '/simulation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/merchant-management'
    | '/model-results'
    | '/order-prediction'
    | '/settings'
    | '/signal-quality'
    | '/simulation'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/merchant-management'
    | '/_app/model-results'
    | '/_app/order-prediction'
    | '/_app/settings'
    | '/_app/signal-quality'
    | '/_app/simulation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/simulation': {
      id: '/_app/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof AppSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signal-quality': {
      id: '/_app/signal-quality'
      path: '/signal-quality'
      fullPath: '/signal-quality'
      preLoaderRoute: typeof AppSignalQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-prediction': {
      id: '/_app/order-prediction'
      path: '/order-prediction'
      fullPath: '/order-prediction'
      preLoaderRoute: typeof AppOrderPredictionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/model-results': {
      id: '/_app/model-results'
      path: '/model-results'
      fullPath: '/model-results'
      preLoaderRoute: typeof AppModelResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/merchant-management': {
      id: '/_app/merchant-management'
      path: '/merchant-management'
      fullPath: '/merchant-management'
      preLoaderRoute: typeof AppMerchantManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMerchantManagementRoute: typeof AppMerchantManagementRoute
  AppModelResultsRoute: typeof AppModelResultsRoute
  AppOrderPredictionRoute: typeof AppOrderPredictionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalQualityRoute: typeof AppSignalQualityRoute
  AppSimulationRoute: typeof AppSimulationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMerchantManagementRoute: AppMerchantManagementRoute,
  AppModelResultsRoute: AppModelResultsRoute,
  AppOrderPredictionRoute: AppOrderPredictionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalQualityRoute: AppSignalQualityRoute,
  AppSimulationRoute: AppSimulationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
